AstaKit:
  FriWahl:
    VoterDirectory:
      importFormats:
        example:
          fieldSeparator: ","
          fieldWrap: "\""
          fields:
            -
              type: "discriminator"
              name: "matriculationNumber"
            -
              # e.g. James P. Hoffmann, Mike Schulz
              type: "property"
              name: "givenName"
            -
              type: "discriminator"
              name: "department"
              failIfMissingValue: true
              preProcessing:
                - trim
              valueMap:
                "School of Scaring": "scaring"
                "School of Engineering": "eng"
                "School of Liberal Arts & Monstrosities": "libart"
                "School of Science": "science"
                "School of Business": "business"
